<?php
namespace SymfonyWorld\WealthyLaughingDuck;
/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Exception\TApplicationException;


interface FinanceServiceIf {
  public function add($n1, $n2);
  public function sub($n1, $n2);
}

class FinanceServiceClient implements \SymfonyWorld\WealthyLaughingDuck\FinanceServiceIf {
  protected $input_ = null;
  protected $output_ = null;

  protected $seqid_ = 0;

  public function __construct($input, $output=null) {
    $this->input_ = $input;
    $this->output_ = $output ? $output : $input;
  }

  public function add($n1, $n2)
  {
    $this->send_add($n1, $n2);
    return $this->recv_add();
  }

  public function send_add($n1, $n2)
  {
    $args = new \SymfonyWorld\WealthyLaughingDuck\FinanceService_add_args();
    $args->n1 = $n1;
    $args->n2 = $n2;
    $bin_accel = ($this->output_ instanceof TProtocol::$TBINARYPROTOCOLACCELERATED) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'add', TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('add', TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }

  public function recv_add()
  {
    $bin_accel = ($this->input_ instanceof TProtocol::$TBINARYPROTOCOLACCELERATED) && function_exists('thrift_protocol_read_binary');
    if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, '\SymfonyWorld\WealthyLaughingDuck\FinanceService_add_result', $this->input_->isStrictRead());
    else
    {
      $rseqid = 0;
      $fname = null;
      $mtype = 0;

      $this->input_->readMessageBegin($fname, $mtype, $rseqid);
      if ($mtype == TMessageType::EXCEPTION) {
        $x = new TApplicationException();
        $x->read($this->input_);
        $this->input_->readMessageEnd();
        throw $x;
      }
      $result = new \SymfonyWorld\WealthyLaughingDuck\FinanceService_add_result();
      $result->read($this->input_);
      $this->input_->readMessageEnd();
    }
    if ($result->success !== null) {
      return $result->success;
    }
    throw new \Exception("add failed: unknown result");
  }

  public function sub($n1, $n2)
  {
    $this->send_sub($n1, $n2);
    return $this->recv_sub();
  }

  public function send_sub($n1, $n2)
  {
    $args = new \SymfonyWorld\WealthyLaughingDuck\FinanceService_sub_args();
    $args->n1 = $n1;
    $args->n2 = $n2;
    $bin_accel = ($this->output_ instanceof TProtocol::$TBINARYPROTOCOLACCELERATED) && function_exists('thrift_protocol_write_binary');
    if ($bin_accel)
    {
      thrift_protocol_write_binary($this->output_, 'sub', TMessageType::CALL, $args, $this->seqid_, $this->output_->isStrictWrite());
    }
    else
    {
      $this->output_->writeMessageBegin('sub', TMessageType::CALL, $this->seqid_);
      $args->write($this->output_);
      $this->output_->writeMessageEnd();
      $this->output_->getTransport()->flush();
    }
  }

  public function recv_sub()
  {
    $bin_accel = ($this->input_ instanceof TProtocol::$TBINARYPROTOCOLACCELERATED) && function_exists('thrift_protocol_read_binary');
    if ($bin_accel) $result = thrift_protocol_read_binary($this->input_, '\SymfonyWorld\WealthyLaughingDuck\FinanceService_sub_result', $this->input_->isStrictRead());
    else
    {
      $rseqid = 0;
      $fname = null;
      $mtype = 0;

      $this->input_->readMessageBegin($fname, $mtype, $rseqid);
      if ($mtype == TMessageType::EXCEPTION) {
        $x = new TApplicationException();
        $x->read($this->input_);
        $this->input_->readMessageEnd();
        throw $x;
      }
      $result = new \SymfonyWorld\WealthyLaughingDuck\FinanceService_sub_result();
      $result->read($this->input_);
      $this->input_->readMessageEnd();
    }
    if ($result->success !== null) {
      return $result->success;
    }
    throw new \Exception("sub failed: unknown result");
  }

}

// HELPER FUNCTIONS AND STRUCTURES

class FinanceService_add_args extends TBase {
  static $_TSPEC;

  public $n1 = null;
  public $n2 = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'n1',
          'type' => TType::I32,
          ),
        2 => array(
          'var' => 'n2',
          'type' => TType::I32,
          ),
        );
    }
    if (is_array($vals)) {
      parent::__construct(self::$_TSPEC, $vals);
    }
  }

  public function getName() {
    return 'FinanceService_add_args';
  }

  public function read($input)
  {
    return $this->_read('FinanceService_add_args', self::$_TSPEC, $input);
  }
  public function write($output) {
    return $this->_write('FinanceService_add_args', self::$_TSPEC, $output);
  }
}

class FinanceService_add_result extends TBase {
  static $_TSPEC;

  public $success = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        0 => array(
          'var' => 'success',
          'type' => TType::I32,
          ),
        );
    }
    if (is_array($vals)) {
      parent::__construct(self::$_TSPEC, $vals);
    }
  }

  public function getName() {
    return 'FinanceService_add_result';
  }

  public function read($input)
  {
    return $this->_read('FinanceService_add_result', self::$_TSPEC, $input);
  }
  public function write($output) {
    return $this->_write('FinanceService_add_result', self::$_TSPEC, $output);
  }
}

class FinanceService_sub_args extends TBase {
  static $_TSPEC;

  public $n1 = null;
  public $n2 = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'n1',
          'type' => TType::I32,
          ),
        2 => array(
          'var' => 'n2',
          'type' => TType::I32,
          ),
        );
    }
    if (is_array($vals)) {
      parent::__construct(self::$_TSPEC, $vals);
    }
  }

  public function getName() {
    return 'FinanceService_sub_args';
  }

  public function read($input)
  {
    return $this->_read('FinanceService_sub_args', self::$_TSPEC, $input);
  }
  public function write($output) {
    return $this->_write('FinanceService_sub_args', self::$_TSPEC, $output);
  }
}

class FinanceService_sub_result extends TBase {
  static $_TSPEC;

  public $success = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        0 => array(
          'var' => 'success',
          'type' => TType::I32,
          ),
        );
    }
    if (is_array($vals)) {
      parent::__construct(self::$_TSPEC, $vals);
    }
  }

  public function getName() {
    return 'FinanceService_sub_result';
  }

  public function read($input)
  {
    return $this->_read('FinanceService_sub_result', self::$_TSPEC, $input);
  }
  public function write($output) {
    return $this->_write('FinanceService_sub_result', self::$_TSPEC, $output);
  }
}


