<?php
namespace SymfonyWorld\WealthyLaughingDuck;

/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Exception\TApplicationException;


final class TCategoryType {
  const INCOME = 1;
  const OUTCOME = 2;
  static public $__names = array(
    1 => 'INCOME',
    2 => 'OUTCOME',
  );
}

class TOutcome extends TBase {
  static $_TSPEC;

  public $amount = null;
  public $user = null;
  public $category = null;
  public $comment = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'amount',
          'type' => TType::DOUBLE,
          ),
        2 => array(
          'var' => 'user',
          'type' => TType::STRING,
          ),
        3 => array(
          'var' => 'category',
          'type' => TType::STRING,
          ),
        4 => array(
          'var' => 'comment',
          'type' => TType::STRING,
          ),
        );
    }
    if (is_array($vals)) {
      parent::__construct(self::$_TSPEC, $vals);
    }
  }

  public function getName() {
    return 'TOutcome';
  }

  public function read($input)
  {
    return $this->_read('TOutcome', self::$_TSPEC, $input);
  }
  public function write($output) {
    return $this->_write('TOutcome', self::$_TSPEC, $output);
  }
}

class TIncome extends TBase {
  static $_TSPEC;

  public $amount = null;
  public $user = null;
  public $category = null;
  public $comment = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'amount',
          'type' => TType::DOUBLE,
          ),
        2 => array(
          'var' => 'user',
          'type' => TType::STRING,
          ),
        3 => array(
          'var' => 'category',
          'type' => TType::STRING,
          ),
        4 => array(
          'var' => 'comment',
          'type' => TType::STRING,
          ),
        );
    }
    if (is_array($vals)) {
      parent::__construct(self::$_TSPEC, $vals);
    }
  }

  public function getName() {
    return 'TIncome';
  }

  public function read($input)
  {
    return $this->_read('TIncome', self::$_TSPEC, $input);
  }
  public function write($output) {
    return $this->_write('TIncome', self::$_TSPEC, $output);
  }
}

class TUser extends TBase {
  static $_TSPEC;

  public $username = null;
  public $fullname = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'username',
          'type' => TType::STRING,
          ),
        2 => array(
          'var' => 'fullname',
          'type' => TType::STRING,
          ),
        );
    }
    if (is_array($vals)) {
      parent::__construct(self::$_TSPEC, $vals);
    }
  }

  public function getName() {
    return 'TUser';
  }

  public function read($input)
  {
    return $this->_read('TUser', self::$_TSPEC, $input);
  }
  public function write($output) {
    return $this->_write('TUser', self::$_TSPEC, $output);
  }
}

class TCategory extends TBase {
  static $_TSPEC;

  public $id = null;
  public $name = null;
  public $parent_id = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'id',
          'type' => TType::I32,
          ),
        2 => array(
          'var' => 'name',
          'type' => TType::STRING,
          ),
        3 => array(
          'var' => 'parent_id',
          'type' => TType::I32,
          ),
        );
    }
    if (is_array($vals)) {
      parent::__construct(self::$_TSPEC, $vals);
    }
  }

  public function getName() {
    return 'TCategory';
  }

  public function read($input)
  {
    return $this->_read('TCategory', self::$_TSPEC, $input);
  }
  public function write($output) {
    return $this->_write('TCategory', self::$_TSPEC, $output);
  }
}

class TDate extends TBase {
  static $_TSPEC;

  public $year = null;
  public $month = null;
  public $day = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'year',
          'type' => TType::I32,
          ),
        2 => array(
          'var' => 'month',
          'type' => TType::I32,
          ),
        3 => array(
          'var' => 'day',
          'type' => TType::I32,
          ),
        );
    }
    if (is_array($vals)) {
      parent::__construct(self::$_TSPEC, $vals);
    }
  }

  public function getName() {
    return 'TDate';
  }

  public function read($input)
  {
    return $this->_read('TDate', self::$_TSPEC, $input);
  }
  public function write($output) {
    return $this->_write('TDate', self::$_TSPEC, $output);
  }
}

class TPeriod extends TBase {
  static $_TSPEC;

  public $from = null;
  public $to = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'from',
          'type' => TType::STRUCT,
          'class' => '\SymfonyWorld\WealthyLaughingDuck\TDate',
          ),
        2 => array(
          'var' => 'to',
          'type' => TType::STRUCT,
          'class' => '\SymfonyWorld\WealthyLaughingDuck\TDate',
          ),
        );
    }
    if (is_array($vals)) {
      parent::__construct(self::$_TSPEC, $vals);
    }
  }

  public function getName() {
    return 'TPeriod';
  }

  public function read($input)
  {
    return $this->_read('TPeriod', self::$_TSPEC, $input);
  }
  public function write($output) {
    return $this->_write('TPeriod', self::$_TSPEC, $output);
  }
}

class TCriteria extends TBase {
  static $_TSPEC;

  public $period = null;
  public $users = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'period',
          'type' => TType::STRUCT,
          'class' => '\SymfonyWorld\WealthyLaughingDuck\TPeriod',
          ),
        2 => array(
          'var' => 'users',
          'type' => TType::LST,
          'etype' => TType::STRUCT,
          'elem' => array(
            'type' => TType::STRUCT,
            'class' => '\SymfonyWorld\WealthyLaughingDuck\TUser',
            ),
          ),
        );
    }
    if (is_array($vals)) {
      parent::__construct(self::$_TSPEC, $vals);
    }
  }

  public function getName() {
    return 'TCriteria';
  }

  public function read($input)
  {
    return $this->_read('TCriteria', self::$_TSPEC, $input);
  }
  public function write($output) {
    return $this->_write('TCriteria', self::$_TSPEC, $output);
  }
}


